// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3461l2uQFBC2EqdnziZlaIveBz-Sn0TU',
    appId: '1:783738136999:web:d57cc08688f9af0ac5ee82',
    messagingSenderId: '783738136999',
    projectId: 'fir-series-b4994',
    authDomain: 'fir-series-b4994.firebaseapp.com',
    storageBucket: 'fir-series-b4994.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEFYKiuiZBxjUuo-1PXe7DwuOKr5lHUEA',
    appId: '1:783738136999:android:5a7993a266ebf11dc5ee82',
    messagingSenderId: '783738136999',
    projectId: 'fir-series-b4994',
    storageBucket: 'fir-series-b4994.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJIBAe-xEdlPe9-BBsCbw_qcJ8qqwV-no',
    appId: '1:783738136999:ios:4906ca6a9e8b961cc5ee82',
    messagingSenderId: '783738136999',
    projectId: 'fir-series-b4994',
    storageBucket: 'fir-series-b4994.appspot.com',
    iosBundleId: 'com.example.courseBasic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJIBAe-xEdlPe9-BBsCbw_qcJ8qqwV-no',
    appId: '1:783738136999:ios:d837c7eea132c357c5ee82',
    messagingSenderId: '783738136999',
    projectId: 'fir-series-b4994',
    storageBucket: 'fir-series-b4994.appspot.com',
    iosBundleId: 'com.example.courseBasic.RunnerTests',
  );
}
